### ISSUE TITLE
Find creator and make offer to do work and post collateral

### ISSUE THREAD

**Issue by xyzerobtc** [zeroauthority-dao/za-website#11]

**Comment by xyzerobtc** [comment]
Scope: 
Call function to the Cerulean-MP clarity contract to lock collateral until the work is completed. 
Show last 4 of tx id for work in progress on creator's profile 
Show last 4 of tx id for work completed on creator's profile 
Give Cerulean reputation +10 to creator for doing work. 
Give Cerulean reputation +2 to client for contracting work. 

Amount:

**Comment by SushilBro** [comment]
"Hi, I'm interested in taking on this project and I have experience working with clarity smart contracts. Could you please provide more information about the scope of work and specific requirements? Once I have a better understanding of the project, I can provide a more accurate estimate of the timeline and budget. Thank you!"

**Comment by xyzerobtc** [comment]
@SushilBro completed user story and tested for bugs.
