### ISSUE TITLE
The "@stacks/blockchain-api-client" is actively monitoring certain transactions, but it is not capturing all subscribed transactions.

### ISSUE THREAD

**Issue by SushilBro** [zeroauthority-dao/za-website#28]
Problem:
In our attempt to listen to real-time transactions using websockets, we receive a response from the called function and update our off-chain database only if the transaction ID (txid) is confirmed in the anchor block. However, we are experiencing a limitation where not all subscribed transactions are being captured.

The code to listen to WebSocket connections is housed in the upsertGig.js file, accessible through this GitHub link: https://github.com/zeroauthority-dao/za-website/blob/Sushil-branch-master/pages/api/upsertGig.js.

**Comment by mefrem** [comment]
Shared as an issue to the relevant repo!

**Comment by xyzerobtc** [comment]
Thanks! @mefrem - can you share the link to the repo you created a new issue?

**Comment by xyzerobtc** [comment]
Thanks for helping us @mefrem we will follow up 

we are building the cerulean marketplace (similar to upwork and linkedin) built on bitcoin.
site: zeroauthority.xyz
testnet: za-website-staging.vercel.app

Thanks again @kenrogers

**Comment by xyzerobtc** [comment]
Title: 
The "@stacks/blockchain-api-client" is actively monitoring certain transactions, but it is not capturing all subscribed transactions.
